src/main/java/com/tave/tavewebsite/global/exception/GlobalExceptionHandler.java, src/main/java/com/tave/tavewebsite/global/s3/config/S3Config.java, src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorException.java, src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorMessage.java, src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java, src/main/resources/application.yml
> - s3 관련 crud 작업 코드 작성
> - application.yml에 최대 업로드 가능 크기 설정
> 예외 처리 클래스를 한 곳에서 관리하기 위해, 추상 클래스를 사용했습니다. static 클래스여서 쓸데없는 메모리 공간을 차지하는 것은 아닌가 걱정했지만, 찾아보니 지연 로딩을 사용하기 때문에 예외가 throw 될 때 까지, 메모리에 할당되지 않는다고 합니다.
=> [Feat] s3 이미지 crud 구현

src/main/java/com/tave/tavewebsite/domain/history/controller/ManagerHistoryController.java, src/main/java/com/tave/tavewebsite/domain/history/controller/NormalHistoryController.java, src/main/java/com/tave/tavewebsite/domain/history/dto/request/HistoryRequestDto.java, src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java, src/main/java/com/tave/tavewebsite/domain/history/entity/History.java, src/main/java/com/tave/tavewebsite/domain/history/exception/HistoryErrorException.java, src/main/java/com/tave/tavewebsite/domain/history/exception/HistoryErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/history/repository/HistoryRepository.java, src/main/java/com/tave/tavewebsite/domain/history/service/HistoryService.java, src/main/java/com/tave/tavewebsite/global/security/config/Config.java, src/main/java/com/tave/tavewebsite/global/security/exception/CustomAuthenticationEntryPoint.java, src/main/java/com/tave/tavewebsite/global/security/filter/JwtAuthenticationFilter.java
> #33 
> Close #33 
> - jwt 토큰중 refresh 토큰만 쿠키에 저장하고 access 토큰은 private 변수로 로컬 스토리지에 저장해서 사용한다면 csrf 토큰은 사용할 이유가 없다. 탈취한 refresh 토큰만으로는 access토큰을 재발급 받을 수 없기 때문이다. 따라서 csrf 토큰을 비활성화 해주었다.
> - 동아리 이력 중 일반회원이 조회하는 엔드포인트의 경우, NormalHistoryController에 정의해줬다.
> - 동아리 이력 중 운영진이 조회하는 엔드포인트의 경우, ManagerHistoryController에 정의해줬다.
=> [Feat] 동아리 이력 crud 구현

build.gradle, src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java, src/main/java/com/tave/tavewebsite/domain/member/dto/request/ResetPasswordReq.java, src/main/java/com/tave/tavewebsite/domain/member/dto/request/ValidateEmailReq.java, src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java, src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/member/exception/ExpiredNumberException.java, src/main/java/com/tave/tavewebsite/domain/member/exception/NotMatchedNumberException.java, src/main/java/com/tave/tavewebsite/domain/member/exception/NotMatchedPassword.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java, src/main/java/com/tave/tavewebsite/global/mail/service/MailService.java, src/main/java/com/tave/tavewebsite/global/redis/utils/RedisUtil.java, src/main/resources/templates/email-verification.html
> #34
> Close #34 
> 이메일 인증을 통한 비밀번호 재설정을 구현
> 이메일로 인증번호 전송 시 필요한 html 구현
> MemberController에 대한 api를 회의를 토대로 수정
> 비밀번호 설정에 필요한 정보를 입력하여 메일을 보내면 다음과 같은 메일 형식이 전송됩니다.(html 추후 수정 예정)
=> [Feat] 이메일 인증 구현

src/main/java/com/tave/tavewebsite/domain/project/controller/ProjectController.java, src/main/java/com/tave/tavewebsite/domain/project/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/project/dto/request/ProjectRequestDto.java, src/main/java/com/tave/tavewebsite/domain/project/dto/response/ProjectResponseDto.java, src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java, src/main/java/com/tave/tavewebsite/domain/project/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/project/exception/ProjectNotFoundException.java, src/main/java/com/tave/tavewebsite/domain/project/repository/CustomProjectRepository.java, src/main/java/com/tave/tavewebsite/domain/project/repository/CustomProjectRepositoryImpl.java, src/main/java/com/tave/tavewebsite/domain/project/repository/ProjectRepository.java, src/main/java/com/tave/tavewebsite/domain/project/service/ProjectService.java, src/main/java/com/tave/tavewebsite/global/common/FieldType.java
> #26
> Close #26
> - 프로젝트 crud
> - 프로젝트 조회 시 페이징 처리, 기수 또는 분야 별 조회
> - S3 이미지 업로드
>
> 1. update 기능 구현 시 DB에 수정사항이 반영되지 않는 문제가 있었습니다. @Transactional 어노테이션을 추가해 해당 메서드 내의 모든 DB 연산을 트랜잭션 내에서 처리하도록 하여 DB 업데이트 문제를 수정했습니다.
> - @Transactional 어노테이션을 추가하기 전에는 updateProject 메서드에서 엔티티 업데이트가 단순히 메모리에서만 이루어졌을 가능성이 있습니다. Spring은 기본적으로 DB 연산을 처리하는 메서드에 트랜잭션을 적용하지 않으면, 해당 메서드가 호출될 때 실제로 데이터베이스에 커밋되지 않을 수 있습니다. 트랜잭션을 사용함으로써 데이터베이스의 상태 일관성을 유지하고, 중간에 발생할 수 있는 오류로부터 보호하며, 엔티티의 변경 사항이 확실하게 DB에 반영되도록 보장할 수 있습니다.
> 2. 응답 메시지를 SuccessMessage 파일에서 불러오는 방식을 사용했습니다.
> - 모든 응답 메시지를 한 곳에서 관리 가능
> - 메시지의 표현이나 형식에 일관성 유지 가능
> - 유지보수 훨씬 간편
=> [Feat] 프로젝트 crud 구현

src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java, src/main/java/com/tave/tavewebsite/domain/member/dto/request/RefreshTokenRequestDto.java, src/main/java/com/tave/tavewebsite/domain/member/dto/response/RefreshResponseDto.java, src/main/java/com/tave/tavewebsite/domain/member/dto/response/SignInResponseDto.java, src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java, src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java, src/main/java/com/tave/tavewebsite/global/security/config/Config.java, src/main/java/com/tave/tavewebsite/global/security/exception/CustomAuthenticationEntryPoint.java, src/main/java/com/tave/tavewebsite/global/security/exception/JwtErrorMessage.java, src/main/java/com/tave/tavewebsite/global/security/exception/JwtValidException.java, src/main/java/com/tave/tavewebsite/global/security/filter/JwtAuthenticationFilter.java, src/main/java/com/tave/tavewebsite/global/security/utils/CookieUtil.java
> #40 
> Close #40 
> - 보안을 위해 리프레시 토큰을 쿠키에 설정하고, 액세스 토큰은 메모리에 저장하도록 변경했다.
> - 리프레시 토큰은 현재 Http Only 옵션이 true로 Secure 옵션이 false로 설정돼있다. Secure 옵션은 https 배포 이후 true로 변경할 예정이다.
> - 코드의 가독성을 위해 Admin 서비스와 Auth 서비스를 분리했다. 
> https://2junbeom.tistory.com/143
=> [Feat] 토큰 저장 위치 변경

src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/member/dto/response/AuthorizedManagerResponseDto.java, src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/member/exception/NotManagerAccessException.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java, src/main/java/com/tave/tavewebsite/domain/project/controller/ProjectController.java
> #43
> Close #43
> - SuccessMessage 추가
> - ErrorMessage 추가
> - deleteManager 메서드 구현
> - 일반 회원 및 다른 운영진이 탈퇴를 처리하지 못하도록 예외 처리
> - ADMIN 권한만 탈퇴 기능 처리할 수 있도록 구현
=> [feat] 운영진 강제 탈퇴 처리 기능 구현

src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/member/exception/NotFoundUnauthorizedManager.java, src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
> #46
> Close #46
> - 대기 중인 운영진 승인 성공하면 MANAGER로 Role 변경
> - 대기 중인 운영진 거절 성공하면 탈퇴 처리
> - 대기 중인 운영진 판별 예외 처리
>
> - approveManager와 rejectManager 모두 데이터베이스에 읽기와 쓰기 작업을 수행합니다.
findById()로 데이터를 조회
approveManager는 updateRole()로 데이터를 수정
rejectManager는 deleteById()로 데이터를 삭제
> - 하나의 논리적인 단위로 실행되어야 하고 중간에 예외 발생 시 롤백 처리 되어야 하기 때문에 @Transactional을 사용했습니다.
=> [feat] 대기 운영진 승인/거절

src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java, src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java, src/main/java/com/tave/tavewebsite/global/redis/utils/RedisUtil.java, src/main/java/com/tave/tavewebsite/global/security/utils/CookieUtil.java
> #50 
> Close #50 
> - 로그아웃 시 리프레시 토큰 쿠키를 삭제하는 로직 추가
> - 레디스 블랙 리스트 템플릿을 삭제하고, 하나의 템플릿으로 통합하였다.
> 레디스 블랙 리스트 템플릿은 오로지 로그아웃만을 위해 사용됩니다. 하지만 로그아웃만을 위해 레디스 서버를 하나 더 띄워서 블랙리스트 템플릿을 유지하는 것은 낭비가 너무 크다는 생각에 하나의 템플릿으로 통합 시켜 하나의 레디스 서버에서 로그아웃을 체크하도록 하였습니다.
=> [Fix] 로그아웃 로직 수정

src/main/java/com/tave/tavewebsite/domain/review/controller/ReviewController.java, src/main/java/com/tave/tavewebsite/domain/review/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/review/dto/response/ReviewIdResponseDto.java, src/main/java/com/tave/tavewebsite/domain/review/dto/response/ReviewManagerResponseDto.java, src/main/java/com/tave/tavewebsite/domain/review/dto/response/ReviewResponseDto.java, src/main/java/com/tave/tavewebsite/domain/review/mapper/ReviewMapper.java, src/main/java/com/tave/tavewebsite/domain/review/service/ReviewService.java
> #53 
> Close #53 
> - ReviewResponsetDto 필드 내용 수정
> - ReviewIdResponseDto 필드 추가
> - 리뷰 조회 API별 반환 메세지 수정
> - 리뷰 생성시 응답 메세지 "리뷰를 생성했습니다"로 수정
리뷰 생성 후 응답에 id가 반환되지 않도록 ReviewResponseDto id 필드를 삭제했습니다.
리뷰를 수정하기 위해서는 Review Id가 필요합니다.   
따라서 관리자가 조회하는 경우에는 Review Id를 반환할 수 있도록 ReviewManagerResponseDto를 추가했습니다.   
관리자가 조회한 페이지에서는 리뷰를 수정할 수 있어야 하기 때문입니다.   
초기 Public과 Private 리뷰 조회 API로 설계를 해뒀습니다.   
중간에 비회원과 관리자가 조회할 수 있는 API로 설계를 변경했는데 응답 메세지는 변경되지 않았습니다.
> - 비회원 리뷰 조회: "공개 후기를 반환합니다."
> - 관리자 리뷰 조회: "모든 후기를 반환합니다."
기존 리뷰 생성 후 응답 메세지는 "14기 후기를 생성합니다.", "13기 후기를 생성합니다." 등 생성한 리뷰의 기수를 동적으로 반환했습니다.
굳이 리뷰 생성 후 응답 메세지에 기수별 정보를 담을 필요가 없고 상수로 통일성을 주는게 좋을 거 같다는 피드백을 반영합니다.   
수정된 응답 메세지는 "후기를 생성합니다." 입니다.
> - 수정 전: "14기 후기를 생성합니다.", "13기 후기를 생성합니다." 
> - 수정 후: "후기를 생성합니다." 
>
=> [Feat] review 수정 사항

src/main/java/com/tave/tavewebsite/domain/history/controller/HistorySuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/history/controller/ManagerHistoryController.java, src/main/java/com/tave/tavewebsite/domain/history/dto/request/HistoryRequestDto.java, src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java, src/main/java/com/tave/tavewebsite/domain/history/entity/History.java, src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java, src/main/java/com/tave/tavewebsite/domain/member/entity/Sex.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/LanguageLevel.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Level.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Question.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/TimeSlot.java
> #55 
> Close #55 
> - History 엔티티에 세부 설명 컬럼이 추가되었습니다.
> - 멤버 엔티티의 NickName 컬럼은 신규 회원이 도입되며, 필수가 아닌 것으로 바뀌었기에 데이터베이스 저장할 때에만 NotNull을 제거해주었습니다. 이후 핸드폰 번호, 생년월일, 성별 등의 칼럼을 추가해주었습니다.
> - 이력서 엔티티를 Resume로 추가하였습니다. 프로그래밍 별 실력과 질문, 면접 가능 시간 엔티티는 모두 일대다 관계로 연관관계 편의 메서드를 강제해주었습니다. 추가적으로 "다" 관계에 있는 엔티티 생성 시 외래키를 강제하기 위해 nullable : false 옵션을 추가하였습니다.
자료형은 모두 List로 선언하였습니다. 질문 엔티티를 HashMap이 아닌 List로 선택한 이유는, 질문을 개별 조회할 일이 없다고 판단했기 때문입니다. 프론트단에서 이력서를 조회할 때 페치 조인으로 모든 컬럼을 한 번에 조회하지 않으면 N+1 문제가 발생하기 때문에, 이력서를 조회할 때 무조건 페치 조인을 사용한다는 가정을 세웠고, 이에 따라 개별 조회를 할 일이 없다는 판단하에 HashMap 자료형 사용이 무의미 하다는 결론을 내렸습니다.
=> [Feat] Hsitory 엔티티 수정 및 Resume 엔티티 생성

build.gradle, src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorException.java, src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorMessage.java, src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
> #57 
> Close #57 
> - 이미지 제공 속도를 최적화 하기 위해 컨트롤러를 통해 받은 이미지를 서비스단에서 webp 확장자로 변경 후 저장하는 로직을 추가하였다.
> - 이미지 저장 시 압축 방식은 손실 압축 방식을 선택하였다. 자세한 내용은 아래 링크에 정리해두었다.
https://2junbeom.tistory.com/162
=> Feat/#57/이미지 확장자 변경

src/main/java/com/tave/tavewebsite/global/redis/config/RedisConfig.java, src/main/java/com/tave/tavewebsite/global/redis/entity/RedisProperties.java, src/main/resources/application.yml
> #65 
> Close #65 
> - Redislabs를 이용하여 레디스를 글로벌 캐시로 전환하였습니다.
> Redislabs에서 Redis 서버 구축하기
- 위의 그림에서 원하는 리전과 옵션을 선택한 후, 바로 아래에 제공되는 30MB를 선택하여 무료 버전을 사용할 수 있다.
- 이때 옵션에 따라 요금제가 적용될 수 있으니 주의해야한다.
- 그렇게 만들어진 데이터베이스에서 필요한 정보는 3가지이다. 엔드포인트, 포트, 비밀번호이다.
- 제공되는 엔드포인트를 통해 Host와 Port를 알 수 있고, Security에 있는 비밀번호를 이용하면 해당 Redis Database로 접근할 수 있다!
이후 application.yml에서 해당 정보들을 기입하고 RedisConfig에 적용하면 글로벌 캐시를 사용할 수 있다!
[Redis를 클라우드로 사용하자](https://inpa.tistory.com/entry/REDIS-%F0%9F%93%9A-Redis%EB%A5%BC-%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90-Redislabs)
=> [Feat] Redis를 클라우드로 사용하도록 구현

src/main/java/com/tave/tavewebsite/domain/review/repository/ReviewRepository.java, src/main/java/com/tave/tavewebsite/domain/review/service/ReviewService.java
> #68 
> Close #68 
> - 이번 PR에서 작업한 내용 간략히 설명해주세요
기존 모든 리뷰를 반환하는 API를
무작위 8개 후기를 반환하도록 수정했습니다.
RANDOM() 을 사용했습니다.
```java
@Query(value = "SELECT * FROM review WHERE is_public = true ORDER BY RANDOM() LIMIT 8", nativeQuery = true)
List<Review> findRandomPublicReviews();
```
MYSQL은 RAND()
PostgreSQL은 RANDOM() 을 사용합니다!
>
=> [FIX]: 리뷰(후기) DB 조회 SQL 수정

src/main/java/com/tave/tavewebsite/domain/review/dto/response/ReviewResponseDto.java, src/main/java/com/tave/tavewebsite/domain/review/mapper/ReviewMapper.java, src/main/java/com/tave/tavewebsite/global/common/FieldType.java
> #76
> Close #76 
> - FieldType이 프론트 측 요청대로 반환되도록 수정
ex) 
- DATAANALYSIS -> Data Analysis
- DEEPLEARNING -> Deep Learning
ENUM 열거형을 변경하게 되면 RDB의 제약조건이 변경됩니다.
따라서 다음과 같이 요구사항을 반영하도록 했습니다.
1. 열거형에 해당하는 Message 값을 추가합니다.
2. ReviewResponseDto에서도 FieldType field 가 아닌 String field로 수정
3. Mapper에서 Review와 ReviewResponseDto를 매핑할 때, FieldType이 아니라 FieldType.getMessage()를 매핑하도록 수정
>
=> Fix/#76/분야 별 반환 문자열 변경

src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/EmailNotificationSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/NormalEmailNotificationController.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/dto/request/EmailNotificationRequeestDto.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/entity/EmailNotification.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/entity/EmailStatus.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/repository/EmailNotificationRepository.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/util/EmailNotificationMapper.java
> #78 
> Close #78 
> - 이메일 알림 신청 엔티티 개발과 이메일을 저장하는 POST 기능을 추가했습니다.
이메일 알림 신청 엔티티의 상태는 이메일 신청 성공, 실패 여부를 판단합니다.
이를 기반으로 재시도를 구현할 것이며
재시도 최대 횟수를 제한하기 위해 재시도 컬럼을 추가했습니다.
=> Feat/#78/신규 지원 이메일 알림

src/main/java/com/tave/tavewebsite/domain/member/dto/request/ValidateEmailReq.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
> #84 
> Close #84 
> - 이메일을 인증하는 과정에서 닉네임이 불필요하다는 의견을 수렴하여 nickname에 대한 로직을 삭제하였습니다.
=> [Fix] 이메일 인증에 불필요한 필드 삭제

src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
> #90 
> Close #90 
> - 회원가입 및 비밀번호 재설정 시 필요한 이메일 인증 API를 하나로 통합하였습니다.
> - 회원가입과 비밀번호 재설정은 각각 이메일 인증이 필요합니다. 하지만 이때 이메일의 DB 내의 존재 여부에 따라 기능이 달라집니다.
> - RequestParam을 사용하여 reset에 대한 값이 "false" or 설정하지 않을 경우에는 회원가입 로직을 수행하고, 
> "true" or any value가 들어갈 경우에는 비밀번호 재설정에 대한 로직을 수행합니다.
=> [fix] 회원가입 및 비밀번호 재설정 API 통합

src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageController.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/LanguageLevelRequestDto.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/response/LanguageLevelResponseDto.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/entity/LanguageLevel.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/entity/ProgramingLanguage.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/repository/LanguageLevelRepository.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/repository/ProgramingLanguageRepository.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/service/ProgramingLanguageService.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/util/LanguageLevelMapper.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Level.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
> #89 
> Close #89 
> - 초기 이력서 생성시 프로그래밍 언어를 모두 0으로 초기화 하여 지원분야에 맞는 프로그래밍 언어 객체를 생성하여 저장합니다.
> - 이후 프론트엔드에서 프로그래밍 언어 요청 시 초기화 시킨 객체를 반환합니다.
> - 프론트엔드에서 사용자가 수정한 프로그래밍 언어 별 실력을 리스트로 받으면 해당 리스트에 맞춰 객체를 수정합니다.
> 수정의 예시입니다.
> 조회의 예시입니다.
> 일대다 관계로 인한 쿼리 수의 증가로 fetch join을 적용하였습니다.
https://2junbeom.tistory.com/193
> 이력서 엔티티 생성 로직이 완성되면 해당 로직에 프로그래밍 언어를 0으로 초기화 하여 객체를 생성시키는 로직 추가
> 이력서 엔티티 조회 시 엔티티 조회에 실패한다면 던질 에러 코드 추가
=> [Feat] 프로그래밍 실력 관련 crud 작업

src/main/java/com/tave/tavewebsite/domain/resume/dto/timeslot/TimeSlotReqDto.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/timeslot/TimeSlotResDto.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/TimeSlot.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/NotValidTimeException.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ResumeNotFoundException.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/UnauthoirzedResumeException.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/UnauthorizedResumeException.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/TimeSlotRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/service/TimeSlotService.java, src/main/java/com/tave/tavewebsite/domain/resume/service/TimeSlotServiceImpl.java, src/main/java/com/tave/tavewebsite/global/security/exception/AuthorizedException.java, src/main/java/com/tave/tavewebsite/global/security/exception/ErrorType.java, src/main/java/com/tave/tavewebsite/global/security/utils/SecurityUtils.java, src/test/java/com/tave/tavewebsite/domain/resume/service/TimeSlotServiceImplTest.java
> #83 
> Close #83 
> - 동아리 지원 시 면접에 대해 가능한 시간대를 생성 및 조회하는 기능을 구현합니다.
> 우선 면접 시간 엔티티에 대한 생성자 빌더 패턴을 적용합니다.
> 후에 면접 시간에 대한 CRU 기능을 구현합니다. 이때 이력서에 대한 유효성 검증을 실시하며 검증이 완료되면 로직을 실행합니다.
> 면접 시간 정보 저장은 stream을 사용하여 간략한 코드로 각 reqDto가 timeSlotRepository에 저장되도록 하였습니다.
> 면접 시간에 대한 기능 테스트를 위해 테스트 클래스를 작성하여 면접 시간 생성에 대한 메서드만 테스트 하였습니다.
> 이때 Mock을 사용하여 가짜 객체를 생성하고 동작을 수행하여 정상적으로 저장되는지 테스트 해보았습니다.
=> [Feat] 면접 기능 구현

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/request/PersonalInfoRequestDto.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/PersonalInfoResponseDto.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidFieldException.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/MemberNotFoundException.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ResumeNotFoundException.java, src/main/java/com/tave/tavewebsite/domain/resume/mapper/ResumeMapper.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #88
> Close #88
> - 지원서 작성 시 회원이 입력해야 할 내용은 학교이름, 전공, 부전공, 지원분야 입니다.
> - memberId를 사용해 지원서 입력, 임시저장 기능을 구현했습니다. 
> - resumeId를 사용해 지원서 조회, 수정, 삭제 기능을 구현했습니다.
> - resume entity에 지원서 입력 시 필요한 field를 구현했습니다. (field max 길이 늘렸습니다.)
> - 지원서에서 사용되는 지원 분야를 FieldType enum으로 정의했습니다.
> - Resume 객체 생성 시 @Builder 패턴을 사용하여 더 직관적이고 안전하게 객체를 생성할 수 있도록 했습니다.
>
=> [feat] 지원서 개인정보 crud

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
> #97
> Close #97
> - 지원서 개인정보 관련 api 엔드포인트를 일반 회원인 /member 로 변경
>
=> [fix] 지원서 개인정보 입력 api 엔드포인트 일반 회원으로 변경

src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
> #90 
> Close #90 
> - 이번 PR에서 작업한 내용 간략히 설명해주세요
RequestBody를 통해 전달해야하는 인증번호 유효검사 API를 GetMapping으로 설정하여 API 통신이 이루어지지 않는 오류가 발생하였습니다.
이를 PostMapping으로 수정하여 통신되도록 하였습니다.
>
=> [Fix] RequestBody를 받기 위한 메서드 유형 수정

src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java, src/test/java/com/tave/tavewebsite/global/s3/service/S3ServiceTest.java
> #90 
> Close #90 
> - 회원가입/비밀번호 찾기 별로 수행하는 한 메서드에 대해 파라미터에 따라 분리하였습니다. 
> - webp 형식으로 변환되는 파일에 대한 테스트 코드를 작성하였습니다. 그 결과, 기존 파일 확장자 + .webp으로 저장이 되는 사항을 발견했습니다.
=> fix: 회원가입 시 이메일 인증 재수정

src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
> #82 
> Close #82 
> -  일반 회원가입 패키지 위치를 수정합니다.
기존 ManagerController에 위치한 **일반 회원가입**을 AuthController로 이동시켰습니다.
최종 엔드포인트는 /v1/auth/normal/signup 입니다.
>
기존 **관리자 회원가입**의 엔드포인트는 /v1/auth/signup입니다.
추가된 코드와 통일성을 맞추기 위해서 /v1/auth/manager/signup 으로 변경하는 건 어떨 지 팀원들 과 이야기 나누고 싶습니다!
``` java
// 기존
// 관리자 회원가입
"/v1/auth/signup"
// 일반 회원가입
"/v1/auth/normal/signup"
// 건의사항
// 관리자 회원가입
"/v1/auth/manager/signup"
// 일반 회원가입
"/v1/auth/normal/signup"
```
=> [fix] 일반 회원가입 패키지 위치 수정

src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java, src/main/java/com/tave/tavewebsite/domain/member/controller/MemberSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/member/dto/request/ResetNormalPasswordRequestDto.java, src/main/java/com/tave/tavewebsite/domain/member/dto/request/ResetPasswordVerifyRequestDto.java, src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
> 86
> Close #86
> - 일반 회원 비밀번호 찾기 로직과 비밀번호 재설정 기능 구현
> - 관리자와 다르게 이름, 이메일, 생년월일 입력받음
> - 이메일과 인증 번호 사용해 인증 번호 확인받음
> - 기존 관리자 비밀번호 재설정 로직과 동일한 방식으로 처리
>
> API 엔드포인트 맞는지 확인 부탁드립니다
=> [feat] 일반회원 비밀번호 찾기

src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageAdminController.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageController.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/ProgramingLanguageRequestDto.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/ProgrammingLanguageByFieldRequestDto.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/response/ProgrammingLanguageResponseDto.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/entity/ProgramingLanguage.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/exception/LanguageErrorException.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/exception/ProgrammingLanguageErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/repository/ProgramingLanguageRepository.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/service/ProgramingLanguageAdminService.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/service/ProgramingLanguageService.java, src/main/java/com/tave/tavewebsite/domain/programinglaunguage/util/LanguageLevelMapper.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java, src/main/java/com/tave/tavewebsite/global/common/FieldType.java
> #110 
> Close #110 
> - 1. 관리자는 다음의 post 요청으로 field 별 질문할 언어의 종류를 설정할 수 있습니다.
> - 2. 생성된 언어는 이력서 생성시 이력서의 필드 값을 기준으로 조회됩니다.
(예를 들어 이력서의 필드값이 백엔드라면, 백엔드에 저장된 언어들이 조회되는 로직입니다.)
> - 3. 조회된 언어들은 saveAll 메서드를 통해 이력서와 연관관계를 가지며 모두 저장됩니다.
> - 4. 주의사항 (field의 이름이 다르다면 조회에 실패하니 field이름에 대한 예외 처리가 잘 이뤄져야 합니다.)
=> [Feat] 이력서 생성시 프로그래밍 언어 초기화 작업

src/main/java/com/tave/tavewebsite/domain/resume/dto/request/PersonalInfoRequestDto.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/FieldTypeInvalidException.java, src/main/java/com/tave/tavewebsite/domain/resume/mapper/ResumeMapper.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #112
> Close #112
> - PersonalInfoService에서 field 값을 처리하는 로직을 FieldType을 직접 사용하는 방식으로 수정했습니다.
> - PersonalInfoRequestDto에서 String 타입으로 받던 field 값을 FieldType enum으로 변경했습니다.
> - Resume 엔티티에서 FieldType을 직접 사용하도록 수정하고, String을 enum으로 처리할 수 있도록 변경했습니다.
> - 프론트에서 보내는 FieldType 값을 직접 enum으로 변환하는 방식으로 수정했습니다.
>
=> [fix] 필드타입 수정

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CreatePersonalInfoResponse.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #114
> Close #114
> - 지원서 작성 시 memberId 기반으로 개인정보 저장 및 분야별 질문 리스트 반환 기능 구현
> - PersonalInfoController에 /resume/{memberId} POST API 추가
> - PersonalInfoService에서 createPersonalInfo() 메소드 내부에 ResumeQuestionResponse 반환 로직 구현
> - ResumeQuestionService를 통해 분야(FieldType)에 따른 공통 및 분야별 질문 생성
>
=> [feat] 이력서 분야별 질문 생성

src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
> #126
> Close #126
> - 기존에 ResumeQuestion과 Resume 간 매핑이 없어 Resume 삭제 시 외래키 제약 조건 위반 발생
> - Resume 삭제 시 연결된 ResumeQuestion도 함께 삭제되도록 수정
> - Member 삭제 시 Resume 및 해당 Resume에 연결된 ResumeQuestion도 같이 삭제되도록 cascade 및 orphanRemoval 설정 추가
> - @oneTomany 연관관계에서 자식 엔티티가 부모에 종속될 경우 cascade와 orphanRemoval 설정 필요, 없으면 삭제 순서 문제로 오류 발생 가능
>
=> [Bug] Resume 삭제 시 FK 제약 오류 발생

src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/controller/InterviewPlaceController.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/request/InterviewPlaceSaveDto.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/response/InterviewPlaceResponse.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/entity/InterviewPlace.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/exception/NotFoundInterviewPlaceException.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/repository/InterviewPlaceRepository.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/service/InterviewPlaceService.java
> #130 
> Close #130
> - 면접 설정 API를 구현했습니다.
면접 설정 페이지를 위한 API 구현
- 위 페이지 구현을 위해 시군구를 나타내는 generalAddress와 상세 주소를 나타내는 detailAddress필드로 주소 필드를 나눴습니다.
- Link 필드는 TEXT로 설정했습니다.
- 일단 면접이 나흘 동안 이루어지는 것을 구현하기 위해 first ~ fourth로 필드에 하드코딩 해두었습니다.
훗날 변경 가능성이 있습니다.
- 면접 정보 수정과 삭제는 보이지 않아 구현하지 않았습니다.
- 면접 정보 조회 시 조건이 명확하지 않아 가장 최근 생성된 면접 정보를 반환하도록 했습니다.
=> Feat 면접 설정 api 구현

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/PersonalInfoResponseDto.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #132
> Close #132
> - 개인정보 조회 시 전체 정보 조회 (기존엔 새로 입력받은 내용만 조회했음)
> - 개인정보 수정 시 memberId로 수정하는 api 추가 (임시저장 전 수정할 경우 위해)
>
=> fix: 전체 개인정보 조회, memberId로 개인정보 수정

src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java, src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionUpdateRequest.java, src/main/java/com/tave/tavewebsite/domain/question/dto/response/QuestionDetailsResponse.java, src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CreatePersonalInfoResponse.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/DetailResumeQuestionResponse.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/AnswerType.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeState.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/AlreadySubmittedResumeException.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #134 
> Close #134 
- 지원서 최종 제출 api 추가
> 지원서 최종 제출 시 상태 변경 후, 수정 불가하도록 설정
> 최종 제출 전까진 redis에 임시저장, 최종 제출 후 DB에 저장되도록 최종 제출 로직 추후 수정할 예정
- 지원서 생성 시 resumeId 응답 바디에 추가
- 질문 답변 타입 필드 추가 `answerType`
>
=> fix: 지원서 수정

src/main/java/com/tave/tavewebsite/domain/finalpass/controller/FinalPassController.java, src/main/java/com/tave/tavewebsite/domain/finalpass/controller/FinalPassSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/finalpass/dto/request/FinalPassRequestDto.java, src/main/java/com/tave/tavewebsite/domain/finalpass/dto/response/FinalPassResponseDto.java, src/main/java/com/tave/tavewebsite/domain/finalpass/entity/FinalPass.java, src/main/java/com/tave/tavewebsite/domain/finalpass/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/finalpass/exception/FinalPassNotFoundException.java, src/main/java/com/tave/tavewebsite/domain/finalpass/mapper/FinalPassMapper.java, src/main/java/com/tave/tavewebsite/domain/finalpass/repository/FinalPassRepository.java, src/main/java/com/tave/tavewebsite/domain/finalpass/service/FinalPassService.java
> #138
> Close #138
> - admin 권한으로 최종 합격 안내 설정 api 구현했습니다.
> - member 권한으로 최종 합격 안내 조회 api 구현했습니다.
> - Entity와 DTO 간 변환 로직을 FinalPassMapper에 집중시켜 코드 중복을 최소화하고자 했습니다.
> - 수동 변환 대신 Mapper를 사용해 가독성 향상 및 변환 오류 가능성을 감소시켰습니다.
>
=> feat: 최종 합격 안내 설정 기능 구현

src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeQuestionJdbcRepository.java
> #153 
> Close #153
> - Resume을 저장할 때 생성되는 ResumeQuestion에 answer_type과 text_length가 저장되지 않는 오류 해결
ResumeQuestion은 성능 향상을 위해 JdbcTemplate을 활용한 BulkInsert를 사용합니다.
작업 중간에 answer_type과 text_length가 추가되었는데 이를 JdbcTemplate bulkinsert sql에도 추가하지 못해 발생한 오류 입니다.
다음과 같이 answer_type과 text_length를 추가해 정상적으로 동작하게 수정했습니다.
```java
String sql = """
INSERT INTO resume_question (question, answer, ordered, resume_id, field_type, answer_type, text_length ,created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
""";
```
>
=> [feat] BulkInsert SQL에 answer_type과 text_length 추가

src/main/java/com/tave/tavewebsite/domain/applicant/history/controller/ApplicantHistoryController.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/controller/ApplicantHistorySuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/dto/request/ApplicantHistoryPatchRequestDto.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/dto/request/ApplicantHistoryPostRequestDto.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/dto/response/ApplicantHistoryResponseDto.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/entity/ApplicantHistory.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/entity/ApplicationStatus.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/exception/ApplicantHistoryErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/exception/ApplicantHistoryException.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/repository/ApplicantHistoryRepository.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/service/ApplicantHistoryService.java, src/main/java/com/tave/tavewebsite/domain/applicant/history/util/ApplicantHistoryMapper.java, src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/request/PersonalInfoCreateRequestDto.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/mapper/ResumeMapper.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #160 
> Close #160 
> - 지원 이력 테이블 제작
> - 이력서 생성 시 지원 이력 테이블 생성
> - 이력서의 member id, generation이 일치하는 지원 이력을 찾아
이력서의 최종 평가를 바탕으로 지원 이력의 상태를 업데이트
=> [Feat] 마이페이지 기능 개발

src/main/java/com/tave/tavewebsite/domain/interviewplace/controller/InterviewPlaceController.java, src/main/java/com/tave/tavewebsite/domain/interviewplace/service/InterviewPlaceService.java
> #184
> Close #184
> - InterviewPlace 조회 API를 구현합니다.
EndPoint: "/v1/manager/interview-place"
> 
```json
{
"time": "2025-06-25T23:20:42.4684869",
"status": 200,
"code": "200",
"message": "면접 장소 정보를 조회합니다",
"result": [
{
"id": 7,
"interviewDay": "2025-08-11",
"generalAddress": "서울시 중구 을지로 100",
"detailAddress": "우랄랄ㄹ라1",
"openChatLink": "https://open.kakao.com/o/somechat",
"code": "A1BDD"
},
{
"id": 8,
"interviewDay": "2025-08-12",
"generalAddress": "서울시 중구 을지로 100",
"detailAddress": "우랄랄ㄹ라2",
"openChatLink": "https://open.kakao.com/o/anotherchat",
"code": "B332"
},
{
"id": 9,
"interviewDay": "2025-08-13",
"generalAddress": "서울시 중구 을지로 100",
"detailAddress": "우랄랄ㄹ라3",
"openChatLink": "https://open.kakao.com/o/somechat",
"code": "A1BD"
}
]
}
```
=> [Feat] interviewplace 조회 API 구현

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeQuestionRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #180 
> Close #180 
> - 개인정보 저장 및 질문 목록 반환하는 api(`/v1/member/info/{memberId}`)에서 같은 `memberId`로 계속 요청하면 해당 `memberId`에 해당하는 `resumeId`에 맞는 질문들이 중복으로 생성되는 문제를 발견하여 중복 생성 방지 로직을 추가했습니다.
> - 질문 목록 반환 시 기존엔 `id` 값이 null로 나오다가 `existsByResumeId` 체크 후 기존 질문을 DB에서 직접 꺼내서 반환하여 `id` 값 누락 문제를 해결할 수 있었습니다.
=> fix: 지원서 질문 중복 생성 방지

src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java, src/main/java/com/tave/tavewebsite/domain/member/dto/response/SignInResponseDto.java, src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeState.java
> #181 
> Close #181 
> - 로그인 시 최종제출 여부 확인할 수 있는 필드 `resumeState` 를 추가했습니다.
> - `ResumeRepository`에서 `Optional<Resume>` 반환에 따른 `AuthService`의 Optional 처리 로직을 적용했습니다.
> - JWT 토큰 생성과 쿠키 세팅 로직을 한 번만 수행하도록 개선했습니다.
=> feat: 최종제출 여부 필드 추가

.github/workflows/TEST-CI-CD.yml
> #189
> Close #189
> - 
Test서버에 Main 브랜치 작업을 반영하기 위해 CI-CD 파이프라인을 구축했습니다.
실제 서버와 달리 ASG를 사용하지 않기 때문에 EC2서버 내부에 deploy.sh 스크립트를 작성 후 실행하도록 했습니다.
>
=> [Feat] TEST-CI-CD.yml 작성

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #201
> Close #201
> - 지원서 생성과 질문 생성 로직을 하나의 트랜잭션으로 통합하여 처리했습니다.
> - `createPersonalInfoAndQuestions()` 메서드 추가 및 기존 메서드 호출 구조를 변경했습니다.
> - 질문 생성 과정에서 예외 발생 시, 이력서 생성도 함께 롤백되도록 개선했습니다.
> - `@Transactional `범위 확장으로 데이터 일관성 및 원자성을 보장하도록 했습니다.
> - 컨트롤러에서 서비스 호출 부분 수정하여 트랜잭션 통합을 반영했습니다.
=> fix: 개인 정보 및 질문 생성 트랜잭션 통합으로 롤백 문제 해결

src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java, src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
> #206
> Close #206
> - 소셜 링크(깃허브, 블로그) 및 포트폴리오 URL 저장 시 DB와 Redis에 동시에 저장하도록 기능 추가
> - 소셜 링크 조회 시 Redis에서 먼저 데이터를 조회하고, 없으면 DB에서 조회하는 로직 구현 (캐싱 효과)
> - 포트폴리오 파일 업로드 후 S3 URL을 DB와 Redis에 저장하도록 처리
>
=> feat: 소셜 링크 및 포트폴리오 임시저장 기능 수정

src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewFinalTestService.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
> #205
> Close #205
> - Interveiwfinal 생성 test 기능 추가
엑셀 과정을 거치지 않고 서류 합격자들의 InterviewFinal을 바로 생성하는 API를 구현했습니다.
베타 테스트에서 사용할 기능이므로 추후 삭제합니다.
>
=> [Feat] Interveiwfinal 생성 test 기능 추가

src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
> #210
> Close #210
> - 소셜 링크 및 포트폴리오 주소를 DB에 저장하는 동시에 Redis 임시저장 데이터(`ResumeTempWrapper`)의 page3에 동기화하여 임시저장 조회 시 최신 데이터가 반영되도록 구현했습니다.
> - 소셜 링크 등록, 수정, 포트폴리오 업로드 시 각각 DB 저장 및 Redis 임시저장 데이터 갱신 로직을 추가했습니다.
> - 기존 Redis 내 임시저장 데이터에서 page3 정보 조회 후, 기존 타임슬롯과 답변은 유지하고 소셜 링크 및 포트폴리오 주소만 업데이트하는 방식으로 구현했습니다.
>
=> fix: 소셜 링크 및 포트폴리오 DB 저장과 Redis 임시저장 동기화 구현

src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/controller/ApplyInitialSetupController.java, src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/controller/ApplyInitialSetupSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/entity/ApplyInitialSetup.java, src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
> #214 
> Close #214
> - 현재 서류 지원이 마감되었는 지 여부를 확인하는 API를 구현했습니다.
아직 서류 지원이 가능한 경우 true, 서류 지원이 마감된 경우 false를 반환합니다.
>
=> [Feat] 서류 제출기한 검증 API

src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CommonResumeResponse.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeListResponse.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeResponse.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/SpecificResumeResponseDto.java, src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
> #203 
> Close #203 
> - 지원서 리스트 조회 기능을 추가했습니다.
> - 지원서 ID 리스트를 받아 해당 지원서들을 조회하는 서비스 메서드를 구현했습니다.
> - 조회된 지원서 리스트를 분야별 질문, 공통 질문으로 분리하여 DTO로 변환했습니다.
> - 응답 포맷 통일을 위해 `ResumeListResponse` DTO 생성 및 적용했습니다.
> - `ResumeListResponse` 내에 `List<ResumeResponse>` 포함하도록 변경했고 `resumeId`, `common`, `specific` 필드를 추가했습니다.
> - 프론트 요구사항에 맞춘 JSON 형식으로 데이터 반환하도록 수정했습니다.
> - Hibernate 통계 로그 활성화 후 SQL 쿼리 실행 횟수를 확인했습니다. (쿼리 실행 로그 첨부했습니다.)
> - @EntityGraph를 적용하여 N+1 문제를 제거하고, Resume + 연관 엔티티들을 단 1개의 쿼리로 가져오도록 최적화했습니다.
=> feat: 지원서 리스트 조회 기능 및 공통/분야별 응답 DTO 분리 구현

src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewExcelController.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/EmptyFileException.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/IsNotXlsxFileException.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewExcelUseCase.java, src/main/java/com/tave/tavewebsite/global/s3/service/S3DownloadSerivce.java, src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java, src/main/resources/application.yml, src/test/java/com/tave/tavewebsite/global/s3/service/S3ServiceTest.java
> #218 
> Close #218 
> - `면접관 전용 면접 시간표` 엑셀 파일을 S3에 업로드 및 다운로드하는 API를 구현했습니다.
S3에 올라가는 면접 파일과 관련된 경로는 환경변수로 주입 받아 사용하도록했습니다.
```java
private static final String INTERVIEW_FORM~ = "example.xls":
```
위와 같이 상수로 선언하여 사용해도 되지만,   
면접 관련 파일에는 지원자들의 개인정보가 포함되어 있기 때문에 보안상의 이유로 환경변수로 처리했습니다.
S3Service에서 업로드 책임을 가지고 S3DownloadService에서 다운로드의 책임을 가지도록 설계했습니다.
추후 S3Service를 S3UploadService로 리팩토링 한다면 두 서비스간 책임이 명확하게 클래스명에 드러날 거 같아 좋을 거 같습니다.
file이 빈 경우와 file이 xlsx이 아닌 경우에 대비해서 유효성 검증 메서드를 추가해 적용했습니다.
```java
private void checkEmptyFile(MultipartFile file) {
if (file.isEmpty()) {
throw new EmptyFileException();
}
}
private void checkIsXLSXFile(MultipartFile file) {
if (!XLSX_APPLICATION_TYPE.equals(file.getContentType())) {
throw new IsNotXlsxFileException();
}
}
```
>
로컬 환경에서 다운로드에 용이하도록 인가 경로를 잠시 …
=> [Feat] 면접관 시간표 파일 업로드 및 다운로드 API

build.gradle, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardController.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/dto/DashboardRatioResDto.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/dto/DashboardResDto.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/entity/Dashboard.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/exception/DashboardErrorException.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/exception/DashboardErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardRepository.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/service/DashboardService.java, src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepositoryImpl.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java, src/main/java/com/tave/tavewebsite/global/redis/utils/RedisUtil.java, src/main/java/com/tave/tavewebsite/global/redisson/RedissonConfig.java, src/main/resources/redisson.yaml
> #226 
> Close #226 
> - 기수 지원 기간 동안의 현황을 한눈에 보기 위해 필요한 대시보드 기능을 구현하였습니다.
>
=> feat: 대시보드 API 구현 및 테스트 완료

src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/EmailNotificationSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/NormalEmailNotificationController.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/dto/response/EmailNotificationReservationResponse.java, src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
> #238 
> Close #238 
> - 신규 모집 시작 이메일 알림의 예약이 되어있는지 아닌지를 판단하는 기능을 개발했습니다.
>
=> [Feat]: 신규모집 예약확인 기능 개발

src/main/java/com/tave/tavewebsite/domain/member/dto/response/SignInResponseDto.java, src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java
> #254 
> Close #254 
> - 로그인 시 응답에 `resumeId` 필드를 추가했습니다.
> - 작성한 지원서가 없으면 0, 있다면 해당 `resumeId` 를 가져오도록 했습니다.
>
=> [feat] 로그인 시 resumeId 응답에 추가

src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepositoryImpl.java, src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeEvaluateService.java
> #245
> Close #245
> - 기존 서류 리스트 조회 api에 `name` 파라미터를 추가했습니다.
```
if (status == null)
return null;
```
이전 코드에서는 `extractedStatus()` 메서드에서 `status`가 null일 때 null을 반환하였는데, 
```
BooleanExpression statusCondition = extractedStatus(status);
if (statusCondition != null) {
condition.and(statusCondition);
}
```
위 코드처럼 null 체크를 하였더라도 `BooleanExpression` 타입 변수를 바로 `.and()` 하는 코드가 있으면, null 값에서 `.and()`를 호출하면서 `NullPointerException`이 발생할 수 있는 문제점이 있었습니다.
```
if (status == null)
return Expressions.asBoolean(true).isTrue(); // 항상 참 반환
```
때문에 null 대신에 항상 참인 조건 (true)을 반환하도록 하여 쿼리에서 아무런 영향을 주지 않고, null 반환으로 인한 `.and()` 호출 시 발생하는 `NullPointerException`을 예방할 수 있도록 수정하였습니다.
>
=> [feat] 지원자 이름 검색 기능 위해 "name" 파라미터 추가

src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/PortfolioUploadResponseDto.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
> #256 
> Close #256 
> - 프론트엔드 측의 요청으로 포트폴리오 업로드 (POST) api 요청 시 응답 메시지와 업로드한 S3url 주소를 응답받도록 수정하였습니다.
> - 포트폴리오 주소만 응답 값에 보여주기 위해 DTO를 추가하였습니다. 
```
{
"time": "2025-07-30T17:02:37.218948",
"status": 200,
"code": "200",
"message": "포트폴리오 업로드에 성공했습니다.",
"result": {
"portfolioUrl": "https://tavebucket.s3.ap-northeast-2.amazonaws.com/afcd2f58-2619-4917-bfc6-2fcba902cdea.pdf"
}
}
```
>
=> [feat] 포트폴리오 업로드 api 요청 시 응답 값 수정

src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/SocialLinksResponseDto.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/wrapper/ResumeTempWrapper.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java, src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidDataOwnerException.java, src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java, src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
> #260 
> Close #260 
> - 임시저장 API에서 `resumeId`와 로그인 사용자의 소유 여부 검증을 추가했습니다.
> - `ResumeAnswerTempService`에 `validateResumeOwnership()` 메서드 추가
>     - `resumeId`로 조회한 이력서가 현재 로그인한 사용자(`memberId`)의 것인지 검증  
>     - Resume가 존재하지 않으면 `ResumeNotFoundException`을,  사용자가 일치하지 않으면 `InvalidDataOwnerException`을 발생시켜 타인의 데이터를 조회하거나 저장하지 못하도록 방지
> - `resumeRepository.findById()`로 조회 후 소유자(`memberId`)가 다를 경우 `InvalidDataOwnerException` 발생하도록 하였습니다.
> - 해당 로직은 임시 저장(`tempSaveAnswers`) 및 임시 조회(`getTempSavedAnswers`) 모두에 적용됩니다.
> - 소셜 주소 저장/조회 시 사용자별 검증 로직을 강화했습니다.
> - 사용자 식별자(`memberId`)를 기반으로 데이터 접근을 제어하도록 하였습니다.
> - 다른 사용자의 `resumeId`로 소셜 주소 및 포트폴리오 저장 또는 조회 시 `InvalidDataOwnerException` 발생하도록 하였습니다.
<hr>
ResumeTempWrapper에 `memberId` 필드를 추가하고,
Redis 키는 `resumeId` 기반으로 단순화했습니다.
- 저장 시점: Redis에 저장되는 …
=> [refactor] 임시저장, 소셜주소 사용자 검증 로직 추가

src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
> #262 
> Close #262 
> - `resumeTimeSlots`와 `member`를 fetch join으로 가져오는 `findByIdWithTimeSlotsAndMember` 메서드를 추가했습니다.
> - `ResumeAnswerTempService`의 DB fallback 로직(`loadFromDatabase`)에 해당 쿼리 메서드를 적용하여, 필요한 최소 fetch만 수행하도록 하였습니다.
> - Lazy 관계(`resumeQuestions`, `languageLevels`)는 @BatchSize 기반으로 지연 로딩하도록 설계하였습니다.
<hr>
> - Hibernate의 SQL 실행 통계(Session Metrics)를 확인해보았습니다.
```
2025-08-01 23:32:10 [http-nio-8080-exec-2] INFO  o.h.e.i.StatisticalLoggingSessionEventListener - Session Metrics {
9210584 nanoseconds spent acquiring 1 JDBC connections;
0 nanoseconds spent releasing 0 JDBC connections;
62750 nanoseconds spent preparing 1 JDBC statements;
10307458 nanoseconds spent executing 1 JDBC statements;
0 nanoseconds spent executing 0 JDBC batches;
0 nanoseconds spent performing 0 L2C puts;
0 …
```
=> [Feat] ResumeTimeSlot과 Member를 함께 조회하는 쿼리 메서드 추가 및 DB fallback 로직에 적용

src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardController.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardSuccessMessage.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/dto/DashboardUpdateDto.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/entity/Dashboard.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardCustomRepository.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardCustomRepositoryImpl.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardRepository.java, src/main/java/com/tave/tavewebsite/domain/apply/dashboard/service/DashboardService.java, src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
> #264 
> Close #264 
> - API 호출을 통해 이력서의 업데이트 사항을 대시보드에 반영하였습니다.
(테스트 완료)
현재 이력서가 한 개 존재하는 상태에서 조회를 하였더니 성공적으로 대시보드에 반영된 것을 확인할 수 있었습니다.
=> feat: 대시보드 업데이트 API 구현

src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java, src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java, src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java, src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
> #268 
> Close #268 
> - 기존 로직은 사용자가 포트폴리오 파일을 업로드한 이후 삭제할 수 없는 문제가 있었습니다.
> - 업로드된 포트폴리오를 null로 업데이트(삭제) 할 수 있도록 수정하였습니다.
`extractKeyFromUrl()`
> - S3 URL에서 파일 key를 추출하기 위한 메서드
> - 파일 삭제 시 S3에서 해당 객체를 정확히 찾아 삭제하기 위해 사용됩니다.
`updatePortfolio()` 메서드 개선
> - 새 파일이 들어오지 않은 경우(null), 기존 포트폴리오 URL이 있다면 S3에서 파일 삭제 후 `resume`의 포트폴리오 필드를 null로 업데이트합니다.
> - 새 파일이 들어온 경우엔 기존 파일 삭제 후 새 파일 업로드 및 URL을 갱신합니다.
>
=> [fix] 포트폴리오 업로드 시 null 값 허용

src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewExcelController.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/S3FileInputStreamDto.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewExcelUseCase.java, src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java, src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeController.java, src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumePortfolioDto.java, src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java, src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeGetService.java, src/main/java/com/tave/tavewebsite/domain/resume/usecase/ResumeUseCase.java, src/main/java/com/tave/tavewebsite/global/s3/service/S3DownloadSerivce.java
> #274
> Close #274
> - 포트폴리오 다운로드 API 구현
프론트측에서 포트폴리오 다운로드 구현이 힘들어 백엔드에서 구현합니다.
>
=> [HOTFIX] 포트폴리오 다운로드 구현
