TAVE-WEBSITE/TAVE-WEBSITE-BE

src/main/java/com/tave/tavewebsite/TaveWebsiteApplication.java
src/main/java/com/tave/tavewebsite/domain/history/entity/History.java
src/main/java/com/tave/tavewebsite/domain/inquiry/Inquiry.java
src/main/java/com/tave/tavewebsite/domain/session/entity/Session.java
src/main/java/com/tave/tavewebsite/domain/study/entity/Study.java

> #3 
> Close #3
> - 이력 엔티티 작성
>
> - 클래스 이름 대문자로 작성했습니다
> - 각 필드에 필요한 nullable, length 제약 사항 설정했습니다
> - Size 어노테이션 사용하는 것이 좋을까요

[feat] 이력 엔티티 작성

---

src/main/java/com/tave/tavewebsite/domain/history/entity/History.java
src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java

> #5
> Close #5
> - 회원 엔티티 작성
> - Builder 사용
>
> 변수가 많아서 빌더 어노테이션 사용했습니다

[feat] 회원 엔티티 작성

---

src/main/java/com/tave/tavewebsite/domain/inquiry/entity/Inquiry.java
src/main/java/com/tave/tavewebsite/domain/member/entity/DepartmentType.java
src/main/java/com/tave/tavewebsite/domain/member/entity/JobType.java
src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
src/main/java/com/tave/tavewebsite/domain/project/entity/FieldType.java
src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java
src/main/java/com/tave/tavewebsite/domain/session/entity/Session.java
src/main/java/com/tave/tavewebsite/domain/study/entity/FieldType.java
src/main/java/com/tave/tavewebsite/domain/study/entity/Study.java

> #7
> Close #7
> - 프로젝트 엔티티 작성
>

[feat] 프로젝트 엔티티

---

src/main/java/com/tave/tavewebsite/global/config/S3Config.java
src/main/resources/application.yml

> #9 
> Close #9
> - aws s3 버킷 액세스 권한 구현
>

[feat] S3 접근 추가

---

src/main/java/com/tave/tavewebsite/global/exception/GlobalExceptionHandler.java

> #17 
> Close #17 
> - GlobalExceptionHandler에 ExceptionResponse가 제대로 반영되어있지 않아 수정했습니다.
>

[Fix] GlobalExceptionHandler 코드 수정

---

src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java
src/main/java/com/tave/tavewebsite/domain/review/entity/Review.java
src/main/java/com/tave/tavewebsite/domain/study/entity/FieldType.java
src/main/java/com/tave/tavewebsite/domain/study/entity/Study.java
src/main/java/com/tave/tavewebsite/global/common/FieldType.java
src/main/java/com/tave/tavewebsite/global/success/SuccessResponse.java
src/main/java/com/tave/tavewebsite/global/success/SuccessResponseStatus.java
src/main/java/com/tave/tavewebsite/global/success/SuccessStatus.java

> #15 
> Close #15 
> - SuccessResponse를 ResponseEntity 대신 작성
> - Review 엔티티 작성
> - FiedType common 클래스로 이동
>

[Feat] Global SuccessResponse 구현

---

src/main/java/com/tave/tavewebsite/domain/history/controller/ManagerHistoryController.java
src/main/java/com/tave/tavewebsite/domain/history/controller/NormalHistoryController.java
src/main/java/com/tave/tavewebsite/domain/history/dto/request/HistoryRequestDto.java
src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java
src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDtoList.java
src/main/java/com/tave/tavewebsite/domain/history/repository/HistoryRepository.java
src/main/java/com/tave/tavewebsite/domain/history/service/HistoryService.java

> #59 
> Close #59 
> - 프론트엔드의 요구 형식에 맞추어 반환 형식 변경
> - 입력되는 값에 한글이 들어가지 않고 기수에 숫자만 들어가도록 패턴 적용

[Fix] 이력 반환 형식 변경

---

.github/workflows/CI-CD.yml
docker-compose.yml
src/main/java/com/tave/tavewebsite/domain/history/controller/NormalHistoryController.java
src/main/java/com/tave/tavewebsite/global/common/controller/HealthCheckController.java

> #64 
> Close #64 
> - 모든 작업 내용과 스크린샷은 아래 블로그에 자세하게 정리해두었습니다.
https://2junbeom.tistory.com/165
추가 논의 사항 ->
타깃 그룹의 헬스 체크를 위해 API를 하나 만들어 두었는데, 따로 패키지를 하나 더 파서 API를 작성하는 게 나을까요?

[Feat]AWS Auto Scaling Group 적용 및 CI/CD 워크 플로우 변경

---

src/main/java/com/tave/tavewebsite/domain/project/dto/response/ProjectResponseDto.java
src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java

> #71
> Close #71
> - 프로젝트 주제와 이름 중복되는 엔티티 하나로 통일
> - 프로젝트 주제 size 100으로 축소
>

[fix] 프로젝트 엔티티 수정

---

src/main/java/com/tave/tavewebsite/domain/study/controller/StudyController.java
src/test/java/com/tave/tavewebsite/domain/study/service/StudyServiceTest.java

> #69 
> Close #69 
> - 스터디 조회에 대한 로직을 수정하였습니다.
1. 스터디 조회 시 기본 페이징 사이즈 MAX로 수정
2. 스터디 조회 로직에 대한 테스트 코드 작성 및 테스트 완료
>

[Fix] 스터디 로직 수정

---

src/main/java/com/tave/tavewebsite/global/security/config/Config.java

> #74 
> Close #74 
> - 도메인 주소를 cors 허용 주소에 포함했습니다.

[fix] cors 주소에 도메인 허가

---

src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
src/main/java/com/tave/tavewebsite/domain/question/entity/QuestionType.java
src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java

> #80 
> Close #80 
> - 저번 회의 때 작성한 erd cloud 기반으로 엔티티 코드를 수정하였습니다.
https://www.erdcloud.com/d/N3Gy9EY449GwYEGo2

[Feat]: 신규 회원 모집 관련 엔티티 코드 수정

---

src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageController.java

> #96 
> Close #96 
> - 각 api 별 필요한 권한에 맞게 엔드포인트를 수정하였습니다.

[fix] 언어 레벨 엔드포인트 각각에 필요한 권한에 맞게 수정

---

src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java

> #101 
> Close #101 
> - History Response Dto에 Last Updated 필드 추가
>

[fix] 변경된 디자인에 맞추어 반환 형식 변경

---

src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CreatePersonalInfoResponse.java
src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java

> #116
> Close #116
> - 전체 운영진 조회는 불필요하다 판단해 삭제
> - 승인 완료/대기 운영진 조회 GET방식에서 POST방식으로 수정
> - 조회 시 `page` 파라미터를 1번부터 시작하도록 처리 (`PageRequest.of(page - 1, size)` 적용)
>

[fix] 승인 대기/완료 운영진 조회 API 방식 수정

---

src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoSuccessMessage.java
src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeQuestionController.java
src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeAnswerTempDto.java
src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeAnswerTempWrapper.java
src/main/java/com/tave/tavewebsite/domain/resume/dto/request/TempPersonalInfoDto.java
src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidPageNumberException.java
src/main/java/com/tave/tavewebsite/domain/resume/exception/TempNotFoundException.java
src/main/java/com/tave/tavewebsite/domain/resume/exception/TempParseFailedException.java
src/main/java/com/tave/tavewebsite/domain/resume/exception/TempSaveFailedException.java
src/main/java/com/tave/tavewebsite/domain/resume/exception/TempSerializeFailedException.java
src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java

> #118
> Close #118
> - 개인정보 저장 시 질문 목록 동시 생성 및 반환 기능 구현
> - 개인정보 임시 저장 및 조회 기능 추가 (Redis 활용)
> - 질문 답변 임시 저장/조회 기능 구현
> - 답변 임시 저장 조회 응답에 페이지 정보 포함하도록 Wrapper 클래스 도입 및 서비스 로직 수정
>

[feat] 이력서 페이지별 조회

---

build.gradle
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/config/EmailNotificationBatchConfig.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/exception/EmailNotificationBatchErrorMessage.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/exception/EmailNotificationBatchException.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/reader/EmailReaderConfig.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/reader/IdRangePartitioner.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/scheduler/EmailBatchScheduler.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/writer/EmailWriterConfig.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/EmailNotificationSuccessMessage.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/NormalEmailNotificationController.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/dto/response/EmailNotificationApplyResponseDto.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/entity/EmailNotification.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/repository/EmailNotificationRepository.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/util/EmailNotificationMapper.java
src/main/java/com/tave/tavewebsite/global/mail/config/SESMailConfig.java
src/main/java/com/tave/tavewebsite/global/mail/service/MailService.java
src/main/java/com/tave/tavewebsite/global/mail/service/SESMailService.java
src/main/java/com/tave/tavewebsite/global/mail/util/SESMailUtil.java
src/main/java/com/tave/tavewebsite/global/redis/config/RedisShedLockConfig.java
src/main/resources/application.yml

> #125 
> Close #125 
> - 스프링 배치를 통한 이메일 전송 코드 작성
> - AWS SES 도입
> - 멀티 스레딩을 통한 병렬 처리
> - 실패한 이메일 전송에 대해 지수 백오프 재시도 도입
> - Scheduled 어노테이션 사용으로 새벽 3시 백그라운드 실행
> - 다중 서버 환경에서 Scheduled 로직 중복 실행을 막기 위한 Shed lock 도입
스프링 배치 도입 및 멀티 스레딩과 동시성 이슈 정리
https://2junbeom.tistory.com/204
SES 도입 및 적절한 스레드, chunk Size 구하는 과정 정리
https://2junbeom.tistory.com/205
Shed Lock 도입 및 미구현 부분 정리
https://2junbeom.tistory.com/206

[Feat] 이메일 대량 발송 기능 구현

---

src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/timetable/InterviewTimeTableDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/timetable/InterviewTimeTableGroupByDayDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/timetable/InterviewTimeTableGroupByTimeDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/timetable/TimeTableMemberDetailDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/timetable/TotalDateTimeDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalRepository.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewGetService.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/utils/InterviewGroupUtil.java

> #162 
> Close #162
> - 면접 정보 시간표 API 구현
다음을 구현하기 위한 API를 구현했습니다.
그룹화 및 Dto 변환을하기 위한 비지니스 로직을 GroupUtil로 책임을 분리했습니다.
비지니스 로직은 다음과 같습니다.
```java
public Map<LocalDate, Map<LocalTime, List<InterviewFinal>>> groupByDateAndTime(List<InterviewFinal> interviewFinalList) {
return interviewFinalList.stream()
.collect(Collectors.groupingBy(
InterviewFinal::getInterviewDate,
Collectors.groupingBy(InterviewFinal::getInterviewTime)
));
}
```
```java
public List<InterviewTimeTableGroupByDayDto> createTimeTableDtoList(
Map<LocalDate, Map<LocalTime, List<InterviewFinal>>>  group
) {
List<InterviewTimeTableGroupByDayDto> groupByDayList = new ArrayList<>();
// ... Map -> Dto 변환 로직
return groupByDayList;
}
```
이 정보들을 InterviewTime에서 가져와야할 지 고민입니다.
```java
// NOTE 이 정보를 InterviewTime 에서 가져와야할 지 고민
public …
```

[Feat] 면접 시간표 API 구현

---

src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeReqDto.java

> #168 
> Close #168 
> - 반환 및 저장 형식에 language levels 필드를 추가하였습니다.
>
저장 시 다음과 같은 형식으로 저장됩니다.

[feat] 임시 저장 형식에 language levels 필드 추가

---

src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
src/main/java/com/tave/tavewebsite/global/mail/service/SESMailService.java

> #175 
> Close #175 
> - 가입 승인 및 거절 템플릿을 SES에 추가
> - 기존 가입 승인 및 거절 템플릿에 메일 전송 코드 추가

[Feat] 가입 승인 거절 메일 기능 개발

---

src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/LanguageLevelRequestDto.java
src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java

> #177 
> Close #177 
> - page2 임시저장 데이터를 `LanguageLevelRequestDto`로 저장하도록 수정했습니다.
> - 포트폴리오 업로드가 이미 있어서 구별하기 쉽게 주석 처리만 하였습니다.
>

feat: 포트폴리오 업로드

---

src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java
src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionUpdateRequest.java
src/main/java/com/tave/tavewebsite/domain/question/dto/response/QuestionDetailsResponse.java
src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java

> #194
> Close #194
> - `QuestionSaveRequest`에 `required` 필드를 추가했습니다.
> - `Question` 엔티티의 `update` 메서드에 `required` 값 반영했습니다.
> - 질문 수정 시 필수 여부도 함께 변경 가능하도록 했습니다.
>

[fix] required 필드 추가 및 엔티티에 반영

---

src/main/java/com/tave/tavewebsite/domain/resume/entity/AnswerType.java
src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java
src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java

> #191 
> Close #191 
> - 이번 PR에서 작업한 내용 간략히 설명해주세요
1. Webp 파일 업로드 시 무손실 방식을 사용하여 화질 저하를 방지
2. ResumeQuestion의 답변 필드 제약조건 해제
>

Fix: 이력서 평가 리스트 조회 필터링 기능 수정

---

src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/scheduler/EmailBatchScheduler.java
src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
src/main/java/com/tave/tavewebsite/domain/resume/batch/controller/RecruitmentBatchSuccessMessage.java
src/main/java/com/tave/tavewebsite/domain/resume/batch/controller/RecruitmentEmailBatchController.java
src/main/java/com/tave/tavewebsite/domain/resume/batch/dto/response/RecruitmentResponseDto.java

> #231 
> Close #231 
> - 이메일 전송 시간을 다음날 00시로 변경하였습니다.
> - 지원 초기설정에서 documentAnouncementFlag 조회 api를 추가했습니다.
> - 지원 초기설정에서 lastAnouncementFlag 조회 api를 추가했습니다.

[Feat]  이메일 발송 시간 수정

---

src/main/java/com/tave/tavewebsite/domain/finalpass/controller/FinalPassController.java
src/main/java/com/tave/tavewebsite/domain/finalpass/entity/FinalPass.java
src/main/java/com/tave/tavewebsite/domain/finalpass/repository/FinalPassRepository.java
src/main/java/com/tave/tavewebsite/domain/finalpass/service/FinalPassService.java

> #241
> Close #241
> - 경로에 `/{id}` 특정 식별자를 추가해서 특정 `id`를 기준으로 조회하도록 수정했습니다.
>

[fix] 최종합격 안내 조회 수정

---

src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalPageDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java

> #249
> Close #249
> - 페이지네이션에서 totalPage가 포함되도록 수정
```json
{
"time": "2025-07-29T16:59:09.7548674",
"status": 200,
"code": "200",
"message": "최종 면접 페이지네이션 데이터를 반환합니다",
"result": {
"totalPage": 2,
"dataList": [
{
"id": 49,
"field": "데이터분석",
"username": "test3",
"sex": "남자",
"university": "가가대학교",
"interviewDate": "2025-08-10 10:00",
"memberId": 7,
"resumeId": 12
},
{
"id": 61,
"field": "데이터분석",
"username": "test3",
"sex": "남자",
"university": "가가대학교",
"interviewDate": "2025-08-10 10:00",
"memberId": 7,
"resumeId": 12
},
{
"id": 50,
"field": "데이터분석",
"username": "test4",
"sex": "남자",
"university": "가가대학교",
"interviewDate": "2025-08-10 14:00",
"memberId": 8,
"resumeId": 13
},
{
"id": 62,
"field": "데이터분석",
"username": "test4",
"sex": "남자",
"university": "가가대학교",
"interviewDate": "2025-08-10 …
```

[Fix] Interviewfinal 페이지네이션 수정

---

src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalEvaluateResDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalResDto.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalCustomRepository.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalCustomRepositoryImpl.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalRepository.java
src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
src/main/java/com/tave/tavewebsite/domain/resume/entity/EvaluationStatus.java
src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java

> #242 
> Close #242 
> - 최종 면접 평가 기능에 대해 면접 인원들을 조회하고, 면접 평가를 진행할 수 있는 기능을 구현했습니다.
>

Feat: 최종면접 평가 리스트 조회
